CI-CD: mat_inf< T, V, N >::iter Class Reference
mat_inf< T, V, N >::iter Class Reference
Public Types
using map_iter
Public Member Functions
iter (map_iter iter)
T & operator* () const
iter & operator++ ()
bool operator!= (const iter &other) const
Private Attributes
map_iter mapIter
Detailed Description
template<typename T, T V, size_t N = 2>
class mat_inf< T, V, N >::iter
Definition at line 25 of file mat_inf.h.
Member Typedef Documentation
map_iter
template<typename T, T V, size_t N = 2> using mat_inf< T, V, N >::iter::map_iter
Initial value:
 typename std::unordered_map<std::vector<int>, T,
                                                     vector_hash>::iterator
Definition at line 27 of file mat_inf.h.
Constructor & Destructor Documentation
iter()
template<typename T, T V, size_t N = 2> mat_inf< T, V, N >::iter::iter (map_iter iter) inline
Definition at line 30 of file mat_inf.h.
: mapIter(iter) {}
Referenced by iter(), operator!=(), and operator++().
Member Function Documentation
operator!=()
template<typename T, T V, size_t N = 2> bool mat_inf< T, V, N >::iter::operator!= (const iter & other) const inline
Definition at line 39 of file mat_inf.h.
{
            return mapIter != other.mapIter;
        }
operator*()
template<typename T, T V, size_t N = 2> T & mat_inf< T, V, N >::iter::operator* () const inline
Definition at line 32 of file mat_inf.h.
{ return mapIter->second; }
operator++()
template<typename T, T V, size_t N = 2> iter & mat_inf< T, V, N >::iter::operator++ () inline
Definition at line 34 of file mat_inf.h.
{
            ++mapIter;
            return *this;
        }
Member Data Documentation
mapIter
template<typename T, T V, size_t N = 2> map_iter mat_inf< T, V, N >::iter::mapIter private
Definition at line 44 of file mat_inf.h.
Referenced by iter(), operator!=(), operator*(), and operator++().
The documentation for this class was generated from the following file:
05_Matrix/mat_inf.h